"""modelos de tarefas e verificacoes mensais

Revision ID: 835357b41528
Revises: 4abf9b9348d2
Create Date: 2026-07-12 11:54:27.130367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835357b41528'
down_revision: Union[str, Sequence[str], None] = '4abf9b9348d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelos_tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_projeto', sa.String(), nullable=False),
    sa.Column('stage_gatilho', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('prioridade', sa.String(), nullable=False),
    sa.Column('responsavel_padrao', sa.String(), nullable=True),
    sa.Column('coluna_inicial', sa.String(), nullable=False),
    sa.Column('dias_prazo', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelos_tarefa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modelos_tarefa_id'), ['id'], unique=False)

    op.create_table('modelos_verificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_projeto', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelos_verificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modelos_verificacao_id'), ['id'], unique=False)

    op.create_table('verificacoes_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.Column('concluida_em', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'competencia', name='uq_verificacao_projeto_competencia')
    )
    with op.batch_alter_table('verificacoes_projeto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verificacoes_projeto_id'), ['id'], unique=False)

    op.create_table('itens_verificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verificacao_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['verificacao_id'], ['verificacoes_projeto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_verificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_verificacao_id'), ['id'], unique=False)

    with op.batch_alter_table('tarefas_projeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prazo', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('modelo_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas_projeto', schema=None) as batch_op:
        batch_op.drop_column('modelo_id')
        batch_op.drop_column('prazo')

    with op.batch_alter_table('itens_verificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_verificacao_id'))

    op.drop_table('itens_verificacao')
    with op.batch_alter_table('verificacoes_projeto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verificacoes_projeto_id'))

    op.drop_table('verificacoes_projeto')
    with op.batch_alter_table('modelos_verificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelos_verificacao_id'))

    op.drop_table('modelos_verificacao')
    with op.batch_alter_table('modelos_tarefa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelos_tarefa_id'))

    op.drop_table('modelos_tarefa')
    # ### end Alembic commands ###
