"""schema inicial

Revision ID: fa1b0d717393
Revises: 
Create Date: 2026-07-12 02:03:21.059517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1b0d717393'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas_dispensados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    with op.batch_alter_table('alertas_dispensados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_dispensados_id'), ['id'], unique=False)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_id'), ['id'], unique=False)

    op.create_table('modelos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('atualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    with op.batch_alter_table('modelos_documento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modelos_documento_id'), ['id'], unique=False)

    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefas_id'), ['id'], unique=False)

    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('pago', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('entrega', sa.Date(), nullable=True),
    sa.Column('escopo', sa.Text(), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projetos_id'), ['id'], unique=False)

    op.create_table('notas_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas_projeto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_projeto_id'), ['id'], unique=False)

    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('pagamento', sa.String(), nullable=True),
    sa.Column('prazo', sa.String(), nullable=True),
    sa.Column('validade_dias', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.Column('plano_gerado_em', sa.DateTime(), nullable=True),
    sa.Column('plano_atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamentos_id'), ['id'], unique=False)

    op.create_table('parcelas_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('pago_em', sa.Date(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcelas_projeto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcelas_projeto_id'), ['id'], unique=False)

    op.create_table('recorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('plano', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dia_vencimento', sa.Integer(), nullable=True),
    sa.Column('inicio', sa.Date(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recorrencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recorrencias_id'), ['id'], unique=False)

    op.create_table('tarefas_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('coluna', sa.String(), nullable=False),
    sa.Column('prioridade', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.Column('atualizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarefas_projeto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefas_projeto_id'), ['id'], unique=False)

    op.create_table('anexos_orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexos_orcamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anexos_orcamento_id'), ['id'], unique=False)

    op.create_table('cobrancas_mensalidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorrencia_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.String(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pago_em', sa.Date(), nullable=True),
    sa.Column('notificado_em', sa.DateTime(), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorrencia_id'], ['recorrencias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recorrencia_id', 'competencia', name='uq_cobranca_recorrencia_competencia')
    )
    with op.batch_alter_table('cobrancas_mensalidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cobrancas_mensalidade_id'), ['id'], unique=False)

    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado', sa.DateTime(), nullable=True),
    sa.Column('atualizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_id'), ['id'], unique=False)

    op.create_table('orcamento_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orcamento_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamento_itens_id'), ['id'], unique=False)

    op.create_table('parcelas_orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('tipo_valor', sa.String(), nullable=False),
    sa.Column('percentual', sa.Float(), nullable=True),
    sa.Column('valor_fixo', sa.Float(), nullable=True),
    sa.Column('tipo_vencimento', sa.String(), nullable=False),
    sa.Column('marco', sa.String(), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcelas_orcamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcelas_orcamento_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcelas_orcamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcelas_orcamento_id'))

    op.drop_table('parcelas_orcamento')
    with op.batch_alter_table('orcamento_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamento_itens_id'))

    op.drop_table('orcamento_itens')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_id'))

    op.drop_table('documentos')
    with op.batch_alter_table('cobrancas_mensalidade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cobrancas_mensalidade_id'))

    op.drop_table('cobrancas_mensalidade')
    with op.batch_alter_table('anexos_orcamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexos_orcamento_id'))

    op.drop_table('anexos_orcamento')
    with op.batch_alter_table('tarefas_projeto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefas_projeto_id'))

    op.drop_table('tarefas_projeto')
    with op.batch_alter_table('recorrencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recorrencias_id'))

    op.drop_table('recorrencias')
    with op.batch_alter_table('parcelas_projeto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcelas_projeto_id'))

    op.drop_table('parcelas_projeto')
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamentos_id'))

    op.drop_table('orcamentos')
    with op.batch_alter_table('notas_projeto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_projeto_id'))

    op.drop_table('notas_projeto')
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projetos_id'))

    op.drop_table('projetos')
    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefas_id'))

    op.drop_table('tarefas')
    with op.batch_alter_table('modelos_documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelos_documento_id'))

    op.drop_table('modelos_documento')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_id'))

    op.drop_table('clientes')
    with op.batch_alter_table('alertas_dispensados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_dispensados_id'))

    op.drop_table('alertas_dispensados')
    # ### end Alembic commands ###
